apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argocd-action
  description: GitHub Action for ArgoCD
  annotations:
    github.com/project-slug: hipagesgroup/argocd-action
spec:
  type: library
  lifecycle: production
  owner: platform
  system: infrastructure-as-code
